M48
; DRILL file KiCad 10.0.1-10.0.1~ubuntu22.04.1 date 2026-05-03T12:38:46
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-03T12:38:46+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1-10.0.1~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X56.71Y-31.4
X62.49Y-31.4
T2
X19.0Y-19.0
X19.0Y-34.0
X74.0Y-19.0
X74.0Y-34.0
M30
